version: '1.0'

services:

  goodbackend:
    build: 
      target: goodbackend
    tty: true
    stdin_open: true
    container_name: goodbackend
    environment:
      - APACHE_RUN_USER=#1000
      - APACHE_RUN_GROUP=#1000
    volumes:
      - ./packages/backend:/var/www//backend
    ports: 
      - 8080:80
    links:
      - mysql
    networks:
      gmnetwork:
        ipv4_address: 172.20.0.11  
  
  goodapi:
    build:
      target: goodapi
    tty: true
    stdin_open: true
    container_name: goodapi
    environment:
      - APACHE_RUN_USER=#1000
      - APACHE_RUN_GROUP=#1000
    volumes:
      - ./packages/api:/var/www/api
    ports: 
      - 8000:80
    links:
      - mysql
    networks:
      gmnetwork:
        ipv4_address: 172.20.0.10
  
  goodfrontend:
    build: 
      target: goodfrontend
    tty: true
    stdin_open: true
    container_name: goodfrontend
    volumes:
      - ./packages/frontend:/usr/src/frontend 
    ports: 
      - 3003:3003
    networks:
      gmnetwork:
        ipv4_address: 172.20.0.12  
    

  mysql:
    image: mysql
    restart: always
    environment:
      - MYSQL_DATABASE=goodmeal
      - MYSQL_ROOT_PASSWORD=mauFJcuf5dhRMQrjj
    ports:
      - '3306:3306'
    networks:
      - gmnetwork

networks:
  gmnetwork:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16





